# Generated by Django 4.1.3 on 2022-11-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_dictcount_alter_dictionary_search_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='search_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Search_count', to='dict.dictcount'),
        ),
    ]
