# Generated by Django 4.1.3 on 2022-11-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_alter_dictcount_search_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictcount',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='search_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Search_count', to='dict.dictcount'),
        ),
    ]
