# Generated by Django 4.1.3 on 2022-11-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_alter_dictcount_search_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='search_count',
        ),
        migrations.AddField(
            model_name='dictcount',
            name='dict_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dict_id', to='dict.dictionary'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='dict_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
