# Generated by Django 4.1.3 on 2022-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_remove_dictionary_search_count_dictcount_dict_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dict_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
