# Generated by Django 4.1.3 on 2022-11-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0010_rename_dict_id_dictionary_search_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='search_count',
        ),
    ]
