# Generated by Django 4.1.3 on 2022-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0011_remove_dictionary_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
