# Generated by Django 4.1.3 on 2022-11-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0013_dictcount_alter_dictionary_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='dict_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
