# Generated by Django 4.1.3 on 2022-11-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0014_dictionary_dict_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='dict_id',
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='DictCount',
        ),
    ]
