# Generated by Django 4.1.3 on 2022-11-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0015_remove_dictionary_dict_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
