# Generated by Django 4.1.3 on 2022-11-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0016_alter_dictionary_search_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='search_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Count', to='dict.dict'),
        ),
    ]
