# Generated by Django 4.1.3 on 2022-11-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0020_rename_search_count_dictionary_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='Dict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Count', to='dict.dict'),
        ),
    ]
