# Generated by Django 4.1.3 on 2022-11-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0022_alter_dictionary_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='Dict',
            new_name='search_count',
        ),
    ]
