# Generated by Django 4.1.3 on 2022-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0023_rename_dict_dictionary_search_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Dict',
        ),
    ]
