# Generated by Django 4.1.3 on 2022-11-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0027_remove_dictionary_search_count_dict_dict_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='ids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
