# Generated by Django 4.1.3 on 2022-11-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0028_dict_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='ids',
        ),
    ]
