# Generated by Django 4.1.3 on 2022-11-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0029_remove_dict_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='dict_id',
        ),
        migrations.AlterField(
            model_name='dict',
            name='dict_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ids', to='dict.dictionary'),
        ),
    ]
