# Generated by Django 4.1.3 on 2022-11-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0031_alter_dict_dict_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='dict_id',
            field=models.IntegerField(),
        ),
    ]
